# Flask Main Application
app:
  build: .
  environment:
    - FONCIER_SETTINGS=/config.py
    - UWSGI_ENABLE_THREADS=1
    - UWSGI_SINGLE_INTERPRETER=1
    - UWSGI_PROCESSES=3
    - UWSGI_THREADS=2
    - UWSGI_MASTER=1
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
  volumes:
    - foncier_staticfiles:/static
    - foncier_extracts:/extracts
  links:
    - ldap
    - redis


# Worker
worker:
  build: celery
  environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
  links:
    - redis


# Proxy
nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  links:
    - app


# sample geOrchestra LDAP
ldap:
  image: georchestra/ldap
  environment:
    - SLAPD_ORGANISATION=georchestra
    - SLAPD_DOMAIN=georchestra.org
    - SLAPD_PASSWORD=secret
    - SLAPD_ADDITIONAL_MODULES=groupofmembers
  volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config:/etc/ldap


# Message broker
redis:
  image: redis:3.2
